blank_issues_enabled: false
contact_links:
  - name: FAQ
    about: Please read our FAQ before filing new issues
    url: https://santi020k.me/linting/troubleshooting
  - name: Getting Started Guide
    about: If you're looking for help setting up, check out our getting started guide
    url: https://santi020k.me
  - name: Ask a question on Discord
    about: If you just want to ask a question, consider asking it on Discord!
    url: https://discord.gg/2JtsXq82
  - name: Ask a question on StackOverflow
    about: If you just want to ask a question, consider asking it on StackOverflow!
    url: https://stackoverflow.com/questions/tagged/eslint
